app/main/forms.py
from flask_wtf import Form
from wtforms.fields import StringField, SubmitField
from wtforms.validators import Required


class LoginForm(Form):
    """Accepts a nickname and a room."""
    name = StringField('Name', validators=[Required()])
    room = StringField('Room', validators=[Required()])
    submit = SubmitField('Enter Chatroom')

app/__init__.py
from flask import Flask
from flask_socketio import SocketIO

socketio = SocketIO()


def create_app(debug=False):
    """Create an application."""
    app = Flask(__name__)
    app.debug = debug
    app.config['SECRET_KEY'] = 'gjr39dkjn344_!67#'

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    socketio.init_app(app)
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes, events

app/main/routes.py
from flask import session, redirect, url_for, render_template, request

from .forms import LoginForm
from flask import Flask, jsonify, request, send_file, render_template, redirect, url_for, make_response
from flask_socketio import SocketIO, send
import numpy as np
from . import main
import matplotlib.pyplot as plt
import tensorflow.keras
from werkzeug.utils import secure_filename
from datetime import datetime
import os
import pathlib
import hashlib

from PIL import Image, ImageOps

np.set_printoptions(suppress=True)
model = tensorflow.keras.models.load_model('keras_model.h5')

import pyrebase

config = {
  "apiKey": "AIzaSyBs6Byg5HK_dlFOSIcmcjsjEyI8zceppYM",
  "authDomain": "med-detect.firebaseapp.com",
  "databaseURL": "https://med-detect.firebaseio.com",
  "storageBucket": "med-detect.appspot.com"
}

firebase = pyrebase.initialize_app(config)


db = firebase.database()
def add_patient(k):
    db.push({"date":k[0], "firstname":k[1], "lastname":k[2], "age":k[3], "height":k[4], "weight":k[5], "diagnosis":k[6], "prob":k[7]})

def get_patients():
    x = db.get().val()
    final = []
    for i in x:
        final.insert(0, [x[i]['date'], x[i]['firstname'], x[i]['lastname'], x[i]['age'], x[i]['height'], x[i]['weight'], x[i]['diagnosis'], x[i]['prob']])
    return final

def get_numbers():
    a = 0
    b = 0

    for i in get_patients():
        if i[6] == "Uninfected":
            a += 1
        else:
            b += 1
    return [a, b]
def get_age_data():
    k = get_patients()
    final = [0, 0, 0, 0, 0]

    for i in k:
        if i[6] == "Parasitized":
            if int(i[3]) < 20:
                final[0] += 1
            elif int(i[3]) >= 20 and int(i[3]) < 40:
                final[1] += 1
            elif int(i[3]) >= 40 and int(i[3]) < 60:
                final[2] += 1
            elif int(i[3]) >= 60 and int(i[3]) < 80:
                final[3] += 1
            elif int(i[3]) >= 80:
                final[4] += 1
    return final
@main.route('/forum', methods=['GET', 'POST'])
def index2():
    """Login form to enter a room."""
    form = LoginForm()
    if form.validate_on_submit():
        session['name'] = form.name.data
        session['room'] = form.room.data
        return redirect(url_for('.chat'))
    elif request.method == 'GET':
        form.name.data = session.get('name', '')
        form.room.data = session.get('room', '')
    return render_template('index2.html', form=form)


@main.route('/chat')
def chat():
    """Chat room. The user's name and room must be stored in
    the session."""
    name = session.get('name', '')
    room = session.get('room', '')
    if name == '' or room == '':
        return redirect(url_for('.index'))
    return render_template('chat.html', name=name, room=room)

@main.route('/')
def index():
    # print(predict('input1.jpg'))
    return render_template('index.html')

@main.route('/upload')
def upload():
    return render_template('upload.html')

@main.route('/trends')
def trends():
    k = get_numbers()
    k1 = get_age_data()
    return render_template('trends.html', a = k[0], b = k[1], p = k1[0], q = k1[1], r = k1[2], s = k1[3], t = k1[4])


@main.route('/download', methods=["GET", "POST"])
def download():
    return redirect("/portfolio")

@main.route('/upload', methods=['GET', 'POST'])
def getupload():
    if request.method == "POST":
        try:
            memory = request.files['memory']
            
            if memory.filename != "":
                memory.save(memory.filename)
                data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
                image = Image.open(memory.filename)
                size = (224, 224)
                image = ImageOps.fit(image, size, Image.ANTIALIAS)
                image_array = np.asarray(image)
                normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1
                data[0] = normalized_image_array
                prediction = model.predict(data)
                
                result = prediction[0]
                # print(result)
                diagnosis = ""
                prob = 0
                if result[0] > result[1]:
                    diagnosis="Uninfected"
                    prob = round(result[0] * 100, 2)
                else:
                    diagnosis = "Parasitized"
                    prob = round(result[1] * 100, 2)
                text = "hello there"

                firstname = request.form["firstname"]
                lastname = request.form["lastname"]
                age = request.form["age"]
                height = request.form["height"]
                weight = request.form["weight"]
                now = datetime.now()
                date = now.strftime("%d/%m/%Y %H:%M:%S")
                new_entry = [date, firstname, lastname, age, height, weight, diagnosis, str(prob)]
                add_patient(new_entry)
                
                
                return render_template('results.html', diagnosis=diagnosis, prob=prob, result=result, text=text)
            
            else:
                return render_template('upload.html', errorMessage="Please upload either a jpeg or png image.")
        except:
            print("EXCEPT")
            return render_template('upload.html', errorMessage="Please upload either a jpeg or png image.")
    return redirect("/upload")

@main.route('/stats')
def stats():
    return render_template('stats.html')

@main.route('/portfolio')
def help():
    
    return render_template('portfolio.html', entries=get_patients())

@main.route('/404')
def error():
    return render_template('404.html')

app/templates/chat.html
<html>
    <head>
        <title>Med Check</title>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        
        <link
          rel="stylesheet"
          href="{{ url_for('static', filename='plugins/bootstrap-4.3.1/css/bootstrap.min.css') }}"
        />
        <link
          rel="stylesheet"
          href="{{ url_for('static', filename='plugins/slick-1.8.1/slick.css') }}"
        />
        <link
          rel="stylesheet"
          href="{{ url_for('static', filename='plugins/meanmenu/meanmenu.css') }}"
        />
        <link
          rel="stylesheet"
          href="{{ url_for('static', filename='fonts/ep-icon-fonts/css/ep-font.css') }}"
        />
        <link
          rel="stylesheet"
          href="{{ url_for('static', filename='fonts/fontawesome-5/css/all.min.css') }}"
        />
        <link
          rel="stylesheet"
          href="{{ url_for('static', filename='css/settings.css') }}"
        />
        <link
          rel="stylesheet"
          href="{{ url_for('static', filename='css/style.css') }}"
        />
        <link
          rel="stylesheet"
          href="{{ url_for('static', filename='css/component.css') }}"
        />
        <link
          rel="stylesheet"
          href="{{ url_for('static', filename='css/demo.css') }}"
        />
        <style>
          @media only screen and (max-width: 600px) {
            #loginHamburger {
              visibility: show;
            }
            #registerHamburger {
              visibility: show;
            }
          }
          @media only screen and (min-width: 600px) {
            #loginHamburger {
              display: none;
            }
            #registerHamburger {
              display: none;
            }
          }
        </style>
        <script type="text/javascript" src="//code.jquery.com/jquery-1.4.2.min.js"></script>
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
        <script type="text/javascript" charset="utf-8">
            var socket;
            $(document).ready(function(){
                socket = io.connect('http://' + document.domain + ':' + location.port + '/chat');
                socket.on('connect', function() {
                    socket.emit('joined', {});
                });
                socket.on('status', function(data) {
                    $('#chat').val($('#chat').val() + '<' + data.msg + '>\n');
                    $('#chat').scrollTop($('#chat')[0].scrollHeight);
                });
                socket.on('message', function(data) {
                    $('#chat').val($('#chat').val() + data.msg + '\n');
                    $('#chat').scrollTop($('#chat')[0].scrollHeight);
                });
                $('#text').keypress(function(e) {
                    var code = e.keyCode || e.which;
                    if (code == 13) {
                        text = $('#text').val();
                        $('#text').val('');
                        socket.emit('text', {msg: text});
                    }
                });
            });
            function leave_room() {
                socket.emit('left', {}, function() {
                    socket.disconnect();

                    // go back to the login page
                    window.location.href = "{{ url_for('main.index') }}";
                });
            }
        </script>
        <style>
          #text {
            border: 3px solid white; 
            -webkit-box-shadow: 
            inset 0 0 8px  rgba(0,0,0,0.1),
                  0 0 16px rgba(0,0,0,0.1); 
            -moz-box-shadow: 
            inset 0 0 8px  rgba(0,0,0,0.1),
                  0 0 16px rgba(0,0,0,0.1); 
            box-shadow: 
            inset 0 0 8px  rgba(0,0,0,0.1),
                  0 0 16px rgba(0,0,0,0.1); 
            padding: 15px;
            background: rgba(255,255,255,0.5);
            background-color: #258aff;
            margin: 0 0 10px 0;
            font-weight: 700;
            font-size: 16px;
            width: 500px;
            color: white;
          }
        </style>
    </head>
    <body>
        <div class="landing-wrapper">
            <header class="site-header">
              <div class="container">
                <div
                  class="row justify-content-center align-items-center position-relative"
                >
                  <div class="col-sm-4 col-6 col-lg-2 col-xl-2 order-lg-1">
                    <div class="brand">
                      <a href="/">
                        <a href="/"><img width="175" style="margin-left: 20px;" src="{{ url_for('static', filename='image/med-detect-reallogo.png') }}"/></a>
                    </a>
                    </div>
                  </div>
                  <div
                    class="col-sm-7 col-lg-3 col-xl-3 offset-xl-1 d-none d-sm-block order-lg-3"
                  >
                    <div class="header-btns">
                      <div class="btn-1 btn-outlined" {{ loginStatus }}>
                        <a>Login</a>
                      </div>
                      <div class="btn-2" {{ loginStatus }} style="background-color: #48bbed;">
                        <a>Sign Up</a>
                      </div>
                      <!-- <div class="btn-2" {{ logoutStatus }}><a href="/logout">Log Out</a></div> -->
                    </div>
                  </div>
                  <div
                    class="col-sm-1 col-6 col-lg-7 col-xl-6 position-static order-lg-2"
                  >
                    <div class="main-navigation">
                      <ul class="main-menu">
                        <li class="menu-item">
                          <a href="/" style="color: #48bbed;">Home</a>
                        </li>
                        <li class="menu-item"><a href="/upload">Upload</a></li>
                        <li class="menu-item">
                          <a href="/portfolio">Portfolio</a>
                        </li>
                        <li class="menu-item">
                          <a href="/trends">Trends</a>
                        </li>
                        <li class="menu-item">
                          <a href="/forum">Forum</a>
                        </li>
                      </ul>
                    </div>
                    <div class="mobile-menu"></div>
                  </div>
                </div>
              </div>
            </header>
            
          <script src="{{ url_for('static', filename='plugins/jquery/jquery.min.js') }}"></script>
          <script src="{{ url_for('static', filename='plugins/jquery/jquery-migrate.min.js') }}"></script>
          <script src="{{ url_for('static', filename='plugins/bootstrap-4.3.1/js/bootstrap.bundle.js') }}"></script>
          <script src="{{ url_for('static', filename='plugins/slick-1.8.1/slick.min.js') }}"></script>
          <script src="{{ url_for('static', filename='plugins/meanmenu/jquery.meanmenu.js') }}"></script>
          <script src="{{ url_for('static', filename='js/active.js') }}"></script>

        <section class="cta-section" style="margin-top:100px;margin-bottom:0px;">
          <div class="container" >
              <div class="cta-inner-wrapper" style="background-color: #48bbed;">
                  <div class="row justify-content-center" >
                      <div class="col-xl-7 col-lg-8">
                          <div class="cta-content" >
                              <!-- <span class="title-small-text">Ready to take action?</span> -->
                              <!-- <h2>Upload an image of the text or copy and paste it in the text box.</h2> -->
                              <p>Welcome to the community chat.</p>
                              <br>
                              <h1 style="color:white;">Chat Room: {{ room }}</h1><br>
                              <textarea id="chat" cols="80" rows="20"></textarea><br><br><br>
                              <input id="text" size="80" placeholder="Enter your message here"><br><br>
                              <a href="#" onclick="leave_room();">Leave this room</a>
      
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </section>

        </div>
    </body>
</html>

app/templates/index2.html
<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Med Check</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/bootstrap-4.3.1/css/bootstrap.min.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/slick-1.8.1/slick.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/meanmenu/meanmenu.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='fonts/ep-icon-fonts/css/ep-font.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='fonts/fontawesome-5/css/all.min.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/settings.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/component.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/demo.css') }}"/>
    <script>(function(e,t,n){var r=e.querySelectorAll("html")[0];r.className=r.className.replace(/(^|\s)no-js(\s|$)/,"$1js$2")})(document,window,0);</script>
    <style>
        #input {
            border: 3px solid white; 
            -webkit-box-shadow: 
            inset 0 0 8px  rgba(0,0,0,0.1),
                  0 0 16px rgba(0,0,0,0.1); 
            -moz-box-shadow: 
            inset 0 0 8px  rgba(0,0,0,0.1),
                  0 0 16px rgba(0,0,0,0.1); 
            box-shadow: 
            inset 0 0 8px  rgba(0,0,0,0.1),
                  0 0 16px rgba(0,0,0,0.1); 
            padding: 15px;
            background: rgba(255,255,255,0.5);
            background-color: #258aff;
            margin: 0 0 10px 0;
            font-weight: 700;
            font-size: 16px;
            width: 500px;
            color: white;
        }

        ::placeholder {
            font-size: 16px;
            padding-top:3px;
            color:rgba(255, 255, 255, 0.5);
        }

        @media only screen and (max-width: 768px) {
            #input {
                width: 250px;
            }
        } 

        @media only screen and (max-width: 600px) {
            #loginHamburger {
                visibility: show;
            }
            #registerHamburger {
                visibility: show;
            }
        }
        
        @media only screen and (min-width: 600px) {
            #loginHamburger {
                display: none;
            }
            #registerHamburger {
                display: none;
            }
        }

        #upload-button {
            background-color: transparent;
        }
        #upload-button:hover {
            background-color: white;
        }
    </style>
    <script type="text/javascript" src="//code.jquery.com/jquery-1.4.2.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
    <script type="text/javascript" charset="utf-8">
        var socket;
        $(document).ready(function(){
            socket = io.connect('http://' + document.domain + ':' + location.port + '/chat');
            socket.on('connect', function() {
                socket.emit('joined', {});
            });
            socket.on('status', function(data) {
                $('#chat').val($('#chat').val() + '<' + data.msg + '>\n');
                $('#chat').scrollTop($('#chat')[0].scrollHeight);
            });
            socket.on('message', function(data) {
                $('#chat').val($('#chat').val() + data.msg + '\n');
                $('#chat').scrollTop($('#chat')[0].scrollHeight);
            });
            $('#text').keypress(function(e) {
                var code = e.keyCode || e.which;
                if (code == 13) {
                    text = $('#text').val();
                    $('#text').val('');
                    socket.emit('text', {msg: text});
                }
            });
        });
        function leave_room() {
            socket.emit('left', {}, function() {
                socket.disconnect();

                // go back to the login page
                window.location.href = "{{ url_for('main.index') }}";
            });
        }
    </script>
</head>
<body>
    <div class="landing-wrapper">
            <header class="site-header">
                    <div class="container">
                        <div class="row justify-content-center align-items-center position-relative">
                            <div class="col-sm-4 col-6 col-lg-2 col-xl-2 order-lg-1">
                                <div class="brand">
                                    <a href="/"><img width="175" style="margin-left: 20px;" src="{{ url_for('static', filename='image/med-detect-reallogo.png') }}"/></a>
                                </div>
                            </div>
                            <div class="col-sm-7 col-lg-3 col-xl-3 offset-xl-1 d-none d-sm-block order-lg-3">
                                <div class="header-btns">
                                  <div class="btn-1 btn-outlined" {{ loginStatus }}><a>Login</a></div>
                                  <div class="btn-2" {{ loginStatus }} style="background-color: #48bbed;"><a>Sign Up</a></div>
                                  <!-- <div class="btn-2" {{ logoutStatus }}><a href="/logout">Log Out</a></div> -->
                              </div>
                            </div>
                            <div class="col-sm-1 col-6 col-lg-7 col-xl-6 position-static order-lg-2">
                                <div class="main-navigation">
                                    <ul class="main-menu">
                                        <li class="menu-item "><a href="/">Home</a></li>
                                        <li class="menu-item "><a href="/upload">Upload</a></li>
                                          <li class="menu-item">
                                            <a href="/portfolio">Portfolio</a>
                                          </li>
                                          <li class="menu-item">
                                            <a href="/trends">Trends</a>
                                          </li>
                                          <li class="menu-item">
                                            <a href="/forum" style="color:#48bbed;">Forum</a>
                                          </li>
                                        </ul>
                                </div>
                                <div class="mobile-menu"></div>
                            </div>
                        </div>
                    </div>
                </header>
                <section class="testimonial-section">
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-8">
                                <div class="section-title">
                                    <h2 style="margin-top: -50px;">Connect through our forums.</h2>
                                    <!-- <p>We designed and tested prototypes that helped identify pain points in the account
                                        creation process. Together, we shaped the new standard.</p> -->
                                </div>
                            </div>
                        </div>
                        <!-- <div class="section-title">
                            We designed and tested prototypes that helped identify pain points in the account
                            creation process. Together, we shaped the new standard
                        </div> -->
                    </div>
                </section>
        <section class="cta-section" style="margin-top:-100px;margin-bottom:100px;">
            <div class="container" >
                <div class="cta-inner-wrapper" style="background-color: #48bbed;">
                    <div class="row justify-content-center" >
                        <div class="col-xl-7 col-lg-8">
                            <div class="cta-content" >
                                <!-- <span class="title-small-text">Ready to take action?</span> -->
                                <!-- <h2>Upload an image of the text or copy and paste it in the text box.</h2> -->
                                <p>Enter a room id to join anonymously!</p>
                                <br>
                                <form method="POST">
                                    {{ form.hidden_tag() }}
                                    <h3 style="color:white;">{{ form.name.label }}:</h3>{{ form.name() }} {% for error in form.name.errors %}{{ error }}{% endfor %}<br><br>
                                    <h3 style="color:white;">{{ form.room.label }}:</h3> {{ form.room() }} {% for error in form.room.errors %}{{ error }}{% endfor %}<br><br><br>
                                    {{ form.submit() }}
                                </form>
        
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="footer-section">
            <div class="container">
                <div class="copyright">
                    <p>©2020 Med Check. All rights reserved. </p>
                </div>
            </div>
        </section>
    </div>
    <script src="{{ url_for('static', filename='plugins/jquery/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='plugins/jquery/jquery-migrate.min.js') }}"></script>
    <script src="{{ url_for('static', filename='plugins/bootstrap-4.3.1/js/bootstrap.bundle.js') }}"></script>
    <script src="{{ url_for('static', filename='plugins/slick-1.8.1/slick.min.js') }}"></script>
    <script src="{{ url_for('static', filename='plugins/meanmenu/jquery.meanmenu.js') }}"></script>
    <script src="{{ url_for('static', filename='js/active.js') }}"></script>
    <script src="{{ url_for('static', filename='js/custom-file-input.js') }}"></script>
</body>

</html>